# Generated by Django 5.1.3 on 2025-10-03 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_patientdetails_date_alter_patientdetails_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='coordinator',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 3, 14, 27, 1, 286052)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinator',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='coordinator_profiles/'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='tat_breached',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='tat_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
