# Generated by Django 5.1.3 on 2025-10-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_bodypart_coordinator_about_coordinator_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='about_me',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='hospital',
            field=models.CharField(default='U4rad Hospital', max_length=200),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='title',
            field=models.CharField(default='Senior Radiologist', max_length=100),
        ),
    ]
